apiVersion: blockstorage.openstack.m.crossplane.io/v1alpha1
kind: QuotasetV3
metadata:
  annotations:
    meta.upbound.io/example-id: blockstorage/v1alpha1/quotasetv3
  labels:
    testing.upbound.io/example-name: quotaset_1
  name: quotaset-1
  namespace: upbound-system
spec:
  forProvider:
    backupGigabytes: 10
    backups: 4
    gigabytes: 100
    groups: 100
    perVolumeGigabytes: 10
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project_1
    snapshots: 4
    volumeTypeQuota:
      gigabytes_ssd: 500
      snapshots_ssd: 10
      volumes_ssd: 30
    volumes: 10

---

apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: ProjectV3
metadata:
  annotations:
    meta.upbound.io/example-id: blockstorage/v1alpha1/quotasetv3
  labels:
    testing.upbound.io/example-name: project_1
  name: project-1
  namespace: upbound-system
spec:
  forProvider:
    name: ${project_1}
