apiVersion: keymanager.openstack.m.crossplane.io/v1alpha1
kind: SecretV1
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/secretv1
  labels:
    testing.upbound.io/example-name: secret_1
  name: secret-1
  namespace: upbound-system
spec:
  forProvider:
    algorithm: aes
    bitLength: 256
    metadata:
      key: foo
    mode: cbc
    name: mysecret
    payloadContentType: text/plain
    payloadSecretRef:
      key: example-key
      name: example-secret
    secretType: passphrase
