apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: QosMinimumBandwidthRuleV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/qosminimumbandwidthrulev2
  labels:
    testing.upbound.io/example-name: minimum_bandwidth_rule_1
  name: minimum-bandwidth-rule-1
spec:
  forProvider:
    minKbps: 200
    qosPolicyId: ${openstack_networking_qos_policy_v2.qos_policy_1.id}

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: QosPolicyV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/qosminimumbandwidthrulev2
  labels:
    testing.upbound.io/example-name: qos_policy_1
  name: qos-policy-1
spec:
  forProvider:
    description: min_kbps
    name: qos_policy_1
