apiVersion: networking.openstack.upbound.io/v1alpha1
kind: QuotaV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/quotav2
  labels:
    testing.upbound.io/example-name: quota_1
  name: quota-1
spec:
  forProvider:
    floatingip: 10
    network: 4
    port: 100
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project_1
    rbacPolicy: 10
    router: 4
    securityGroup: 10
    securityGroupRule: 100
    subnet: 8
    subnetpool: 2

---

apiVersion: identity.openstack.upbound.io/v1alpha1
kind: ProjectV3
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/quotav2
  labels:
    testing.upbound.io/example-name: project_1
  name: project-1
spec:
  forProvider:
    name: ${project_1}

---

