apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: RouterV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerv2
  labels:
    testing.upbound.io/example-name: router_1
  name: router-1
spec:
  forProvider:
    adminStateUp: true
    externalNetworkId: f67f0d72-0ddf-11e4-9d95-e1f29f417e2f
    name: my_router
