apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: SubnetRouteV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/subnetroutev2
  labels:
    testing.upbound.io/example-name: subnet_route_1
  name: subnet-route-1
spec:
  forProvider:
    destinationCidr: 10.0.1.0/24
    nextHop: 192.168.199.254
    subnetId: ${openstack_networking_subnet_v2.subnet_1.id}

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/subnetroutev2
  labels:
    testing.upbound.io/example-name: network_1
  name: network-1
spec:
  forProvider:
    adminStateUp: "true"
    name: network_1

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: RouterV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/subnetroutev2
  labels:
    testing.upbound.io/example-name: router_1
  name: router-1
spec:
  forProvider:
    adminStateUp: "true"
    name: router_1

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/subnetroutev2
  labels:
    testing.upbound.io/example-name: subnet_1
  name: subnet-1
spec:
  forProvider:
    cidr: 192.168.199.0/24
    ipVersion: 4
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
