/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	resource "github.com/crossplane/upjet/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ContainerV1.
func (mg *ContainerV1) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.SecretRefs); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SecretRefs[i3].SecretRef),
			Extract:      resource.ExtractParamPath("secret_ref", true),
			Reference:    mg.Spec.ForProvider.SecretRefs[i3].SecretRefRef,
			Selector:     mg.Spec.ForProvider.SecretRefs[i3].SecretRefSelector,
			To: reference.To{
				List:    &SecretV1List{},
				Managed: &SecretV1{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SecretRefs[i3].SecretRef")
		}
		mg.Spec.ForProvider.SecretRefs[i3].SecretRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SecretRefs[i3].SecretRefRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SecretRefs); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SecretRefs[i3].SecretRef),
			Extract:      resource.ExtractParamPath("secret_ref", true),
			Reference:    mg.Spec.InitProvider.SecretRefs[i3].SecretRefRef,
			Selector:     mg.Spec.InitProvider.SecretRefs[i3].SecretRefSelector,
			To: reference.To{
				List:    &SecretV1List{},
				Managed: &SecretV1{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SecretRefs[i3].SecretRef")
		}
		mg.Spec.InitProvider.SecretRefs[i3].SecretRef = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SecretRefs[i3].SecretRefRef = rsp.ResolvedReference

	}

	return nil
}
