apiVersion: identity.openstack.upbound.io/v1alpha1
kind: ApplicationCredentialV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/applicationcredentialv3
  labels:
    testing.upbound.io/example-name: swift
  name: swift
spec:
  forProvider:
    description: Swift technical application credential
    expiresAt: "2019-02-13T12:12:12Z"
    name: swift
    roles:
    - swiftoperator
    secretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

