apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: InheritRoleAssignmentV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/inheritroleassignmentv3
  labels:
    testing.upbound.io/example-name: role_assignment_1
  name: role-assignment-1
spec:
  forProvider:
    domainId: default
    roleId: ${openstack_identity_role_v3.role_1.id}
    userId: ${openstack_identity_user_v3.user_1.id}

---

apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: RoleV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/inheritroleassignmentv3
  labels:
    testing.upbound.io/example-name: role_1
  name: role-1
spec:
  forProvider:
    domainId: default
    name: role_1

---

apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: UserV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/inheritroleassignmentv3
  labels:
    testing.upbound.io/example-name: user_1
  name: user-1
spec:
  forProvider:
    domainId: default
    name: user_1
