apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: UserMembershipV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/usermembershipv3
  labels:
    testing.upbound.io/example-name: user_membership_1
  name: user-membership-1
spec:
  forProvider:
    groupId: ${openstack_identity_group_v3.group_1.id}
    userId: ${openstack_identity_user_v3.user_1.id}

---

apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: GroupV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/usermembershipv3
  labels:
    testing.upbound.io/example-name: group_1
  name: group-1
spec:
  forProvider:
    description: group 1
    name: group_1

---

apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: ProjectV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/usermembershipv3
  labels:
    testing.upbound.io/example-name: project_1
  name: project-1
spec:
  forProvider:
    name: project_1

---

apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: RoleAssignmentV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/usermembershipv3
  labels:
    testing.upbound.io/example-name: role_assignment_1
  name: role-assignment-1
spec:
  forProvider:
    groupId: ${openstack_identity_group_v3.group_1.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project_1
    roleId: ${openstack_identity_role_v3.role_1.id}

---

apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: RoleV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/usermembershipv3
  labels:
    testing.upbound.io/example-name: role_1
  name: role-1
spec:
  forProvider:
    name: role_1

---

apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: UserV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/usermembershipv3
  labels:
    testing.upbound.io/example-name: user_1
  name: user-1
spec:
  forProvider:
    defaultProjectId: ${openstack_identity_project_v3.project_1.id}
    name: user_1
