apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: LoadbalancerV2
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/loadbalancerv2
  labels:
    testing.upbound.io/example-name: lb_1
  name: lb-1
spec:
  forProvider:
    vipSubnetId: d9415786-5f1a-428b-b35f-2f1523e146d2
