apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: MemberV2
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/memberv2
  labels:
    testing.upbound.io/example-name: member_1
  name: member-1
spec:
  forProvider:
    address: 192.168.199.23
    poolId: 935685fb-a896-40f9-9ff4-ae531a3a00fe
    protocolPort: 8080
