apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: MonitorV2
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv2
  labels:
    testing.upbound.io/example-name: monitor_1
  name: monitor-1
spec:
  forProvider:
    delay: 20
    maxRetries: 5
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pool_1
    timeout: 10
    type: PING
