apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: PoolV2
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/poolv2
  labels:
    testing.upbound.io/example-name: pool_1
  name: pool-1
spec:
  forProvider:
    lbMethod: ROUND_ROBIN
    listenerId: d9415786-5f1a-428b-b35f-2f1523e146d2
    persistence:
    - cookieName: testCookie
      type: APP_COOKIE
    protocol: HTTP
