/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RoleAssignmentV3InitParameters struct {

	// The domain to assign the role in.
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// The group to assign the role to.
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The project to assign the role in.
	// +crossplane:generate:reference:type=ProjectV3
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a ProjectV3 to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a ProjectV3 to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The role to assign.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// The user to assign the role to.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type RoleAssignmentV3Observation struct {

	// The domain to assign the role in.
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// The group to assign the role to.
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The project to assign the role in.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The role to assign.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// The user to assign the role to.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type RoleAssignmentV3Parameters struct {

	// The domain to assign the role in.
	// +kubebuilder:validation:Optional
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// The group to assign the role to.
	// +kubebuilder:validation:Optional
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The project to assign the role in.
	// +crossplane:generate:reference:type=ProjectV3
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a ProjectV3 to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a ProjectV3 to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The role to assign.
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// The user to assign the role to.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// RoleAssignmentV3Spec defines the desired state of RoleAssignmentV3
type RoleAssignmentV3Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RoleAssignmentV3Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleAssignmentV3InitParameters `json:"initProvider,omitempty"`
}

// RoleAssignmentV3Status defines the observed state of RoleAssignmentV3.
type RoleAssignmentV3Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoleAssignmentV3Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RoleAssignmentV3 is the Schema for the RoleAssignmentV3s API. Manages a V3 Role assignment within OpenStack Keystone.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,openstack}
type RoleAssignmentV3 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleId) || (has(self.initProvider) && has(self.initProvider.roleId))",message="spec.forProvider.roleId is a required parameter"
	Spec   RoleAssignmentV3Spec   `json:"spec"`
	Status RoleAssignmentV3Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleAssignmentV3List contains a list of RoleAssignmentV3s
type RoleAssignmentV3List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleAssignmentV3 `json:"items"`
}

// Repository type metadata.
var (
	RoleAssignmentV3_Kind             = "RoleAssignmentV3"
	RoleAssignmentV3_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoleAssignmentV3_Kind}.String()
	RoleAssignmentV3_KindAPIVersion   = RoleAssignmentV3_Kind + "." + CRDGroupVersion.String()
	RoleAssignmentV3_GroupVersionKind = CRDGroupVersion.WithKind(RoleAssignmentV3_Kind)
)

func init() {
	SchemeBuilder.Register(&RoleAssignmentV3{}, &RoleAssignmentV3List{})
}
