/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DatabaseV1InitParameters struct {

	// The ID for the database instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-openstack/apis/db/v1alpha1.InstanceV1
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a InstanceV1 in db to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a InstanceV1 in db to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// A unique name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Openstack region resource is created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type DatabaseV1Observation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID for the database instance.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// A unique name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Openstack region resource is created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type DatabaseV1Parameters struct {

	// The ID for the database instance.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-openstack/apis/db/v1alpha1.InstanceV1
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a InstanceV1 in db to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a InstanceV1 in db to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// A unique name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Openstack region resource is created in.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// DatabaseV1Spec defines the desired state of DatabaseV1
type DatabaseV1Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DatabaseV1Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatabaseV1InitParameters `json:"initProvider,omitempty"`
}

// DatabaseV1Status defines the observed state of DatabaseV1.
type DatabaseV1Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DatabaseV1Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DatabaseV1 is the Schema for the DatabaseV1s API. Manages a V1 database resource within OpenStack.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,openstack}
type DatabaseV1 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DatabaseV1Spec   `json:"spec"`
	Status DatabaseV1Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabaseV1List contains a list of DatabaseV1s
type DatabaseV1List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DatabaseV1 `json:"items"`
}

// Repository type metadata.
var (
	DatabaseV1_Kind             = "DatabaseV1"
	DatabaseV1_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DatabaseV1_Kind}.String()
	DatabaseV1_KindAPIVersion   = DatabaseV1_Kind + "." + CRDGroupVersion.String()
	DatabaseV1_GroupVersionKind = CRDGroupVersion.WithKind(DatabaseV1_Kind)
)

func init() {
	SchemeBuilder.Register(&DatabaseV1{}, &DatabaseV1List{})
}
