apiVersion: orchestration.openstack.crossplane.io/v1alpha1
kind: StackV1
metadata:
  annotations:
    meta.upbound.io/example-id: orchestration/v1alpha1/stackv1
  labels:
    testing.upbound.io/example-name: stack_1
  name: stack-1
spec:
  forProvider:
    disableRollback: true
    environmentOpts:
      Bin: |2+

    name: stack_1
    parameters:
      length: 4
    templateOpts:
      Bin: |
        heat_template_version: 2013-05-23
        parameters:
          length:
            type: number
        resources:
          test_res:
            type: OS::Heat::TestResource
          random:
            type: OS::Heat::RandomString
            properties:
              length: {get_param: length}
    timeout: 30
