/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
Copyright 2025 Yannick Schlosser, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SecgroupV2InitParameters struct {

	// Whether or not to delete the default
	// egress security rules. This is false by default. See the below note
	// for more information.
	DeleteDefaultRules *bool `json:"deleteDefaultRules,omitempty" tf:"delete_default_rules,omitempty"`

	// A unique name for the security group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique name for the security group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The region in which to obtain the V2 networking client.
	// A networking client is needed to create a port. If omitted, the
	// region argument of the provider is used. Changing this creates a new
	// security group.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Indicates if the security group is stateful or
	// stateless. Update of the stateful argument is allowed when there is no port
	// associated with the security group. Available only in OpenStack environments
	// with the stateful-security-group extension. Defaults to true.
	Stateful *bool `json:"stateful,omitempty" tf:"stateful,omitempty"`

	// A set of string tags for the security group.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The owner of the security group. Required if admin
	// wants to create a port for another tenant. Changing this creates a new
	// security group.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type SecgroupV2Observation struct {

	// The collection of tags assigned on the security group, which have
	// been explicitly and implicitly added.
	// +listType=set
	AllTags []*string `json:"allTags,omitempty" tf:"all_tags,omitempty"`

	// Whether or not to delete the default
	// egress security rules. This is false by default. See the below note
	// for more information.
	DeleteDefaultRules *bool `json:"deleteDefaultRules,omitempty" tf:"delete_default_rules,omitempty"`

	// A unique name for the security group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A unique name for the security group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The region in which to obtain the V2 networking client.
	// A networking client is needed to create a port. If omitted, the
	// region argument of the provider is used. Changing this creates a new
	// security group.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Indicates if the security group is stateful or
	// stateless. Update of the stateful argument is allowed when there is no port
	// associated with the security group. Available only in OpenStack environments
	// with the stateful-security-group extension. Defaults to true.
	Stateful *bool `json:"stateful,omitempty" tf:"stateful,omitempty"`

	// A set of string tags for the security group.
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The owner of the security group. Required if admin
	// wants to create a port for another tenant. Changing this creates a new
	// security group.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type SecgroupV2Parameters struct {

	// Whether or not to delete the default
	// egress security rules. This is false by default. See the below note
	// for more information.
	// +kubebuilder:validation:Optional
	DeleteDefaultRules *bool `json:"deleteDefaultRules,omitempty" tf:"delete_default_rules,omitempty"`

	// A unique name for the security group.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A unique name for the security group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The region in which to obtain the V2 networking client.
	// A networking client is needed to create a port. If omitted, the
	// region argument of the provider is used. Changing this creates a new
	// security group.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Indicates if the security group is stateful or
	// stateless. Update of the stateful argument is allowed when there is no port
	// associated with the security group. Available only in OpenStack environments
	// with the stateful-security-group extension. Defaults to true.
	// +kubebuilder:validation:Optional
	Stateful *bool `json:"stateful,omitempty" tf:"stateful,omitempty"`

	// A set of string tags for the security group.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The owner of the security group. Required if admin
	// wants to create a port for another tenant. Changing this creates a new
	// security group.
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

// SecgroupV2Spec defines the desired state of SecgroupV2
type SecgroupV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SecgroupV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecgroupV2InitParameters `json:"initProvider,omitempty"`
}

// SecgroupV2Status defines the observed state of SecgroupV2.
type SecgroupV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecgroupV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecgroupV2 is the Schema for the SecgroupV2s API. Manages a V2 Neutron security group resource within OpenStack.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,openstack}
type SecgroupV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SecgroupV2Spec   `json:"spec"`
	Status SecgroupV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecgroupV2List contains a list of SecgroupV2s
type SecgroupV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecgroupV2 `json:"items"`
}

// Repository type metadata.
var (
	SecgroupV2_Kind             = "SecgroupV2"
	SecgroupV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecgroupV2_Kind}.String()
	SecgroupV2_KindAPIVersion   = SecgroupV2_Kind + "." + CRDGroupVersion.String()
	SecgroupV2_GroupVersionKind = CRDGroupVersion.WithKind(SecgroupV2_Kind)
)

func init() {
	SchemeBuilder.Register(&SecgroupV2{}, &SecgroupV2List{})
}
