apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: SecgroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/secgroupv2
  labels:
    testing.upbound.io/example-name: secgroup_1
  name: secgroup-1
spec:
  forProvider:
    description: my security group
    name: my_secgroup
    rule:
    - cidr: 0.0.0.0/0
      fromPort: 22
      ipProtocol: tcp
      toPort: 22
    - cidr: 0.0.0.0/0
      fromPort: 80
      ipProtocol: tcp
      toPort: 80
