apiVersion: lb.openstack.m.crossplane.io/v1alpha1
kind: QuotaV2
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/quotav2
  labels:
    testing.upbound.io/example-name: quota_1
  name: quota-1
  namespace: upbound-system
spec:
  forProvider:
    healthMonitor: 10
    l7Policy: 11
    l7Rule: 12
    listener: 7
    loadbalancer: 6
    member: 8
    pool: 9
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project_1

---

apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: ProjectV3
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/quotav2
  labels:
    testing.upbound.io/example-name: project_1
  name: project-1
  namespace: upbound-system
spec:
  forProvider:
    name: project_1
