apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: FloatingipAssociateV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/floatingipassociatev2
  labels:
    testing.upbound.io/example-name: fip_1
  name: fip-1
spec:
  forProvider:
    floatingIp: 1.2.3.4
    portId: ${openstack_networking_port_v2.port_1.id}

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: PortV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/floatingipassociatev2
  labels:
    testing.upbound.io/example-name: port_1
  name: port-1
spec:
  forProvider:
    networkId: a5bbd213-e1d3-49b6-aed1-9df60ea94b9a
