apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: QosBandwidthLimitRuleV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/qosbandwidthlimitrulev2
  labels:
    testing.upbound.io/example-name: bw_limit_rule_1
  name: bw-limit-rule-1
spec:
  forProvider:
    direction: egress
    maxBurstKbps: 300
    maxKbps: 3000
    qosPolicyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: qos_policy_1

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: QosPolicyV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/qosbandwidthlimitrulev2
  labels:
    testing.upbound.io/example-name: qos_policy_1
  name: qos-policy-1
spec:
  forProvider:
    description: bw_limit
    name: qos_policy_1
