apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: SecgroupRuleV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/secgrouprulev2
  labels:
    testing.upbound.io/example-name: secgroup_rule_1
  name: secgroup-rule-1
spec:
  forProvider:
    direction: ingress
    ethertype: IPv4
    portRangeMax: 22
    portRangeMin: 22
    protocol: tcp
    remoteIpPrefix: 0.0.0.0/0
    securityGroupId: ${openstack_networking_secgroup_v2.secgroup_1.id}

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: SecgroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/secgrouprulev2
  labels:
    testing.upbound.io/example-name: secgroup_1
  name: secgroup-1
spec:
  forProvider:
    description: My neutron security group
    name: secgroup_1
