apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: TrunkV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/trunkv2
  labels:
    testing.upbound.io/example-name: trunk_1
  name: trunk-1
spec:
  forProvider:
    adminStateUp: "true"
    name: trunk_1
    portId: ${openstack_networking_port_v2.parent_port_1.id}
    subPort:
    - portId: ${openstack_networking_port_v2.subport_1.id}
      segmentationId: 1
      segmentationType: vlan

---

apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: InstanceV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/trunkv2
  labels:
    testing.upbound.io/example-name: instance_1
  name: instance-1
spec:
  forProvider:
    name: instance_1
    network:
    - port: ${openstack_networking_port_v2.parent_port_1.id}
    securityGroupsRefs:
    - name: example

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/trunkv2
  labels:
    testing.upbound.io/example-name: network_1
  name: network-1
spec:
  forProvider:
    adminStateUp: "true"
    name: network_1

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: PortV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/trunkv2
  labels:
    testing.upbound.io/example-name: parent_port_1
  name: parent-port-1
spec:
  forProvider:
    adminStateUp: "true"
    name: parent_port_1
    networkId: ${openstack_networking_network_v2.network_1.id}

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: PortV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/trunkv2
  labels:
    testing.upbound.io/example-name: subport_1
  name: subport-1
spec:
  forProvider:
    adminStateUp: "true"
    name: subport_1
    networkId: ${openstack_networking_network_v2.network_1.id}

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/trunkv2
  labels:
    testing.upbound.io/example-name: subnet_1
  name: subnet-1
spec:
  forProvider:
    cidr: 192.168.1.0/24
    enableDhcp: true
    ipVersion: 4
    name: subnet_1
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
    noGateway: true
