apiVersion: identity.openstack.crossplane.io/v1alpha1
kind: RoleV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/rolev3
  labels:
    testing.upbound.io/example-name: role_1
  name: role-1
spec:
  forProvider:
    name: role_1
