apiVersion: sharedfilesystem.openstack.crossplane.io/v1alpha1
kind: SharenetworkV2
metadata:
  annotations:
    meta.upbound.io/example-id: sharedfilesystem/v1alpha1/sharenetworkv2
  labels:
    testing.upbound.io/example-name: sharenetwork_1
  name: sharenetwork-1
spec:
  forProvider:
    description: test share network
    name: test_sharenetwork
    neutronNetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
    neutronSubnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_1

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  annotations:
    meta.upbound.io/example-id: sharedfilesystem/v1alpha1/sharenetworkv2
  labels:
    testing.upbound.io/example-name: network_1
  name: network-1
spec:
  forProvider:
    adminStateUp: "true"
    name: network_1

---

apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: SubnetV2
metadata:
  annotations:
    meta.upbound.io/example-id: sharedfilesystem/v1alpha1/sharenetworkv2
  labels:
    testing.upbound.io/example-name: subnet_1
  name: subnet-1
spec:
  forProvider:
    cidr: 192.168.199.0/24
    ipVersion: 4
    name: subnet_1
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1
