apiVersion: db.openstack.crossplane.io/v1alpha1
kind: ConfigurationV1
metadata:
  annotations:
    meta.upbound.io/example-id: db/v1alpha1/configurationv1
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    configuration:
    - name: max_connections
      value: 200
    datastore:
    - type: mysql
      version: mysql-5.7
    description: description
    name: test
