apiVersion: db.openstack.crossplane.io/v1alpha1
kind: UserV1
metadata:
  annotations:
    meta.upbound.io/example-id: db/v1alpha1/userv1
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    databases:
    - testdb
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: basic
    name: basic
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
