apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: MonitorV2
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/monitorv2
  labels:
    testing.upbound.io/example-name: monitor_1
  name: monitor-1
spec:
  forProvider:
    delay: 20
    maxRetries: 5
    poolId: ${openstack_lb_pool_v2.pool_1.id}
    timeout: 10
    type: PING
