apiVersion: keymanager.openstack.crossplane.io/v1alpha1
kind: ContainerV1
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/containerv1
  labels:
    testing.upbound.io/example-name: tls_1
  name: tls-1
spec:
  forProvider:
    name: tls
    secretRefs:
    - name: certificate
      secretRefSelector:
        matchLabels:
          testing.upbound.io/example-name: certificate_1
    - name: private_key
      secretRefSelector:
        matchLabels:
          testing.upbound.io/example-name: private_key_1
    - name: intermediates
      secretRefSelector:
        matchLabels:
          testing.upbound.io/example-name: intermediate_1
    type: certificate

---

apiVersion: keymanager.openstack.crossplane.io/v1alpha1
kind: SecretV1
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/containerv1
  labels:
    testing.upbound.io/example-name: certificate_1
  name: certificate-1
spec:
  forProvider:
    name: certificate
    payloadContentType: text/plain
    payloadSecretRef:
      key: attribute.cert.pem
      name: example-secret
      namespace: upbound-system
    secretType: certificate

---

apiVersion: keymanager.openstack.crossplane.io/v1alpha1
kind: SecretV1
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/containerv1
  labels:
    testing.upbound.io/example-name: intermediate_1
  name: intermediate-1
spec:
  forProvider:
    name: intermediate
    payloadContentType: text/plain
    payloadSecretRef:
      key: attribute.intermediate-ca.pem
      name: example-secret
      namespace: upbound-system
    secretType: certificate

---

apiVersion: keymanager.openstack.crossplane.io/v1alpha1
kind: SecretV1
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/containerv1
  labels:
    testing.upbound.io/example-name: private_key_1
  name: private-key-1
spec:
  forProvider:
    name: private_key
    payloadContentType: text/plain
    payloadSecretRef:
      key: attribute.cert-key.pem
      name: example-secret
      namespace: upbound-system
    secretType: private

---

apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: ListenerV2
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/containerv1
  labels:
    testing.upbound.io/example-name: listener_1
  name: listener-1
spec:
  forProvider:
    defaultTlsContainerRef: ${openstack_keymanager_container_v1.tls_1.container_ref}
    loadbalancerId: ${openstack_lb_loadbalancer_v2.lb_1.id}
    name: https
    protocol: TERMINATED_HTTPS
    protocolPort: 443

---

apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: LoadbalancerV2
metadata:
  annotations:
    meta.upbound.io/example-id: keymanager/v1alpha1/containerv1
  labels:
    testing.upbound.io/example-name: lb_1
  name: lb-1
spec:
  forProvider:
    name: loadbalancer
    vipSubnetId: ${data.openstack_networking_subnet_v2.subnet_1.id}
