apiVersion: dns.openstack.m.crossplane.io/v1alpha1
kind: RecordsetV2
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/recordsetv2
  labels:
    testing.upbound.io/example-name: rs_example_com
  name: rs-example-com
  namespace: upbound-system
spec:
  forProvider:
    description: An example record set
    name: rs.example.com.
    records:
    - 10.0.0.1
    ttl: 3000
    type: A
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_zone

---

apiVersion: dns.openstack.m.crossplane.io/v1alpha1
kind: ZoneV2
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/recordsetv2
  labels:
    testing.upbound.io/example-name: example_zone
  name: example-zone
  namespace: upbound-system
spec:
  forProvider:
    description: a zone
    email: email2@example.com
    name: example.com.
    ttl: 6000
    type: PRIMARY
