apiVersion: dns.openstack.m.crossplane.io/v1alpha1
kind: ZoneV2
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/zonev2
  labels:
    testing.upbound.io/example-name: example_com
  name: example-com
  namespace: upbound-system
spec:
  forProvider:
    description: An example zone
    email: jdoe@example.com
    name: example.com.
    ttl: 3000
    type: PRIMARY
