apiVersion: objectstorage.openstack.crossplane.io/v1alpha1
kind: TempurlV1
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/tempurlv1
  labels:
    testing.upbound.io/example-name: obj_tempurl
  name: obj-tempurl
spec:
  forProvider:
    container: tf-test-container-1
    method: post
    object: test/default.json
    ttl: 20

---

apiVersion: objectstorage.openstack.crossplane.io/v1alpha1
kind: ContainerV1
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/tempurlv1
  labels:
    testing.upbound.io/example-name: container_1
  name: container-1
spec:
  forProvider:
    metadata:
      Temp-URL-Key: testkey
    name: test

---

apiVersion: objectstorage.openstack.crossplane.io/v1alpha1
kind: ObjectV1
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/tempurlv1
  labels:
    testing.upbound.io/example-name: object_1
  name: object-1
spec:
  forProvider:
    containerName: test
    content: Hello, world!
    name: test
