/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
Copyright 2025 Yannick Schlosser, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *L7PolicyV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *L7RuleV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ListenerV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadbalancerV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MembersV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MemberV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MonitorV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PoolV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *QuotaV2) Hub() {}
