/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ClustertemplateV1) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterV1) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NodegroupV1) Hub() {}
