/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *GroupV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RuleV2) Hub() {}
