apiVersion: identity.openstack.m.crossplane.io/v1alpha1
kind: EC2CredentialV3
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/ec2credentialv3
  labels:
    testing.upbound.io/example-name: ec2_key1
  name: ec2-key1
  namespace: upbound-system
spec:
  forProvider: {}
