apiVersion: compute.openstack.m.crossplane.io/v1alpha1
kind: InterfaceAttachV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/interfaceattachv2
  labels:
    testing.upbound.io/example-name: ai_1
  name: ai-1
  namespace: upbound-system
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance_1
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: network_1

---

apiVersion: compute.openstack.m.crossplane.io/v1alpha1
kind: InstanceV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/interfaceattachv2
  labels:
    testing.upbound.io/example-name: instance_1
  name: instance-1
  namespace: upbound-system
spec:
  forProvider:
    name: instance_1
    securityGroupsRefs:
    - name: example

---

apiVersion: networking.openstack.m.crossplane.io/v1alpha1
kind: NetworkV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/interfaceattachv2
  labels:
    testing.upbound.io/example-name: network_1
  name: network-1
  namespace: upbound-system
spec:
  forProvider:
    adminStateUp: "true"
    name: network_1
