apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: InstanceV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/instancev2
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    flavorId: "3"
    imageId: ad091b52-742f-469e-8f3c-fd81cadf0743
    keyPairSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    metadata:
      this: that
    name: basic
    network:
    - name: my_network
    securityGroups:
    - default
