apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: ServergroupV2
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/servergroupv2
  labels:
    testing.upbound.io/example-name: test-sg
  name: test-sg
spec:
  forProvider:
    name: my-sg
    policies:
    - anti-affinity
