/*
Copyright 2022 Upbound Inc.
Copyright 2023 Jakob Schlagenhaufer, Jan Dittrich
Copyright 2025 Yannick Schlosser, Jan Dittrich
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ImageAccessAcceptV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ImageAccessV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ImageV2) Hub() {}
