apiVersion: images.openstack.crossplane.io/v1alpha1
kind: ImageAccessV2
metadata:
  annotations:
    meta.upbound.io/example-id: images/v1alpha1/imageaccessv2
  labels:
    testing.upbound.io/example-name: rancheros_member
  name: rancheros-member
spec:
  forProvider:
    imageId: ${openstack_images_image_v2.rancheros.id}
    memberId: bed6b6cbb86a4e2d8dc2735c2f1000e4

---

apiVersion: images.openstack.crossplane.io/v1alpha1
kind: ImageV2
metadata:
  annotations:
    meta.upbound.io/example-id: images/v1alpha1/imageaccessv2
  labels:
    testing.upbound.io/example-name: rancheros
  name: rancheros
spec:
  forProvider:
    containerFormat: bare
    diskFormat: qcow2
    imageSourceUrl: https://releases.rancher.com/os/latest/rancheros-openstack.img
    name: RancherOS
    properties:
      key: value
    visibility: shared
